mondrum.seqctl.playstart();
1::second => now;
chout <= "stop" <= IO.newline();
mondrum.seqctl.stop();
1::second => now;
chout <= "playpause" <= IO.newline();
mondrum.seqctl.playpause();
1::second => now;
chout <= "stop" <= IO.newline();
mondrum.seqctl.stop();
chout <= "stop" <= IO.newline();
mondrum.seqctl.stop();
1::second => now;
chout <= "playpause" <= IO.newline();
mondrum.seqctl.playpause();
3::second => now;
chout <= "playstart" <= IO.newline();
mondrum.seqctl.playstart();
6::second => now;
